### ISSUE TITLE
Should dispose the TelemetryReporter

### ISSUE THREAD

**Issue by jdneo** [Eskibear/vscode-extension-telemetry-wrapper#18]
According to the implementation: https://github.com/Microsoft/vscode-extension-telemetry/blob/6ea39e70f0eef767a02c2d15f0a27c6cc7a1cc7a/src/telemetryReporter.ts#L110

We need to dispose the TelemetryReporter

**Comment by Eskibear** [comment]
Implemented in #19 , shipped with v0.3.2
