### ISSUE TITLE
Too much duplicate code for vscode commands and custom operation

### ISSUE THREAD

**Issue by andxu** [Eskibear/vscode-extension-telemetry-wrapper#21]
for examples in https://github.com/Microsoft/vscode-java-dependency/pull/71, there are duplicate code make the telemetry not very clean.

**Comment by Eskibear** [comment]
an API `instrumentOperationAsVsCodeCommand ` has been provided.
see: https://github.com/Eskibear/vscode-extension-telemetry-wrapper/blob/46710a5120afe1a2e4cfa1f582eae6c64bf85712/src/next/index.ts#L115
