### ISSUE TITLE
Add capability to allow custom disabled telemetry list

### ISSUE THREAD

**Issue by jdneo** [Eskibear/vscode-extension-telemetry-wrapper#43]
1. The telemetry wrapper has its default disabled list
   - e.g. a RegExp: `/path must include project and resource name: \/.*/gi`
3. There is an API to let users overwrite the list

**Comment by Eskibear** [comment]
how about I add API allowing you to register such patterns? E.g. 
`addSensitvePattern(pattern: RegExp)`

**Comment by jdneo** [comment]
Sounds good.

**Comment by Eskibear** [comment]
Instead of directly remove matched result, I'm thinking whether below proposal would be more powerful and flexible.

```ts
addReplacePattern(pattern: RegExp, replaceString: string)
```

E.g. Replace `/path must include project and resource name: \/.*/gi` with "path must include reousrce name" . Then you know what's redacted.

**Comment by Eskibear** [comment]
interesting, vscode-extension-telemetry@0.5.0 now also supports this...
https://github.com/microsoft/vscode-extension-telemetry/releases/tag/v0.5.0
