### ISSUE TITLE
Features/APIs Discussion

### ISSUE THREAD

**Issue by Eskibear** [Eskibear/vscode-extension-telemetry-wrapper#7]
Please discuss about any new features or API changes here according to your use cases. 
If necessary, create new issues for your requirements and link them back here.

**Comment by Eskibear** [comment]
In the `next` version, the wrapper would ensure consistent telemetry format. Following is a draft of the design.

## For a complete operation
#### Type of operations:
* Extension Activation
* VS Code commands
* ...
#### Workflow
For an operation, make sure to send telemetry on `start`, `error`, `end`.
```typescript
function wholeFlow(...args: any[]) :any {
    let error = undefined;
    let operationId = <a unique id>;
    try {
        // send "opStart" telemetry.
        /**
         * perform the operation, throw something if error occurs.
         */
    } catch (e) {
        error = e;
        // send "error" telemetry.
    } finally {
        // send "opEnd" telemetry with/without error information.
    }
}
```
#### Telemetry specs
Here defines 3 types of telemetry events, namely `opStart`, `opEnd`, `error`.
* **opStart**.  Sent just before starting an operation. 
```typescript
interface opStart {
    customDimensions: {
        oId: string;        // A unique Id.
        oName: string;      // Name of operation.
                            // For extension activation, use "activation".
                            // For registered VS Code commands, use command name.
    }
    customMeasurements: {
    }
}
```
* **opEnd**.  Sent just after an operation ends. The field `errorCode` indicates whether there's error occurred during the operation. 
```typescript
interface opEnd {
    customDimensions: {
        oId: string;        // The unique Id same with that in opStart.
        oName: string;      // Name of operation.
                            // For extension activation, use "activation".
                            // For registered VS Code commands, use command name.
        errorCode: string;  // Preserve 0 for no error, 1 for general error.
        message?: string;   // Error message if provided.
        stack?: string      // JSON string of the callstack if error occurs.
    }
    customMeasurements: {
        duration: number;   // Time cost in milliseconds.
    }
}
```
* **error**. Sent when error occurs during the operation. In this event, value of `errorCode` cannot be 0. 
```typescript
interface error {
    errorCode: string;  // 0 is not allowed (indicating no error), 1 for general error.
    message?: string;   // Error message if provided.
    stack?: string      // JSON string of the callstack if error occurs.
}
```

## Under discussion
### LSP request/response
### DAP request/response

**Comment by Eskibear** [comment]
Following is a list of proposed APIs provided by this wrapper.

## APIs for VS Code Command.
* **getWrappedCommand**. This API wraps your command with common logic to send `opStart` and `opEnd` telemetry data. During your command, if any object is thrown, it will be caught as an error, the wrapper function sends an `error` telemetry data immediately according to the error, and appends it in `opEnd`.

    ```typescript
    type Callback = (...args: any[]) => any;

    export function getWrappedCommand(commandName: string, cb: Callback): Callback {
        return async (...args: any[]) => {
            let error = undefined;
            let oid = getUUID();
            const startAt: number = Date.now();
            try {
                sendOpStart(id, commandName);
                return await cb(...args);
            } catch (e) {
                error = e;
                sendError(error);
            } finally {
                const duration = Date.now() - startAt();
                sendOpEnd(oid, commandName, duration, error);
            }
        }
    };
    ```

**Comment by akaroml** [comment]
Proposal for handling user errors.
### Analysis
An error usually occurs in deep call stack. It's not possible for top level routines to tell whether an error is cause by a user or the underlying system. So only the actual application code knows how to classify those errors.
On the other hand, we are not able to associate an error with an operation ID natually in JavaScript. The only channel to transfer error is using exceptions. So we need to leverage exceptions to tell when an error happens.
### Solution
When an error occurs, the function that can identify a user error needs to convert the raw error object to a user error object and throw the new object instead.
```js
function foo() {
  // try open file
  try {
    File.open('some file');
  } catch (e) {
    let error = e;
    if (e instanceof AccessViolationException) {
      error = new UserError(e);
    }
    // throw the new error to top handler
    throw error;
  }
}
```
When top handler receives an error, it can tell whether there is a user errory by performing type check:
```js
funtion rootOp() {
  try {
  } catch (e) {
    if (e instanceof UserError) {
      // mark user error
    }
    sendError(e);
  } finally {
  }
}
```
